/* ============================================================
   ANGELLI PRODUCTIONS — Commercial Work
   ------------------------------------------------------------
   EDIT THIS BY HAND, OR USE THE CURATION TOOL:
       http://localhost:8765/curate.html
   The tool writes straight back to this file.

   ONE SHOOT = ONE PROJECT = ONE THUMBNAIL. Hovering a thumbnail
   cycles through that shoot; clicking opens it in the lightbox.

     title    — shown under the thumbnail
     client   — brand, e.g. "Charlotte Tilbury" (optional)
     year     — e.g. "2025" (optional)
     category — "campaigns" | "product" | "beauty" | "fashion"
     images   — array of paths. THE FIRST ONE IS THE COVER.
     featured — add `featured: true` to put a project on SELECTED.
   ============================================================ */

const COMMERCIAL_PROJECTS = [

  {
    title: "Charlotte Tilbury",
    featured: true,
    client: "Charlotte Tilbury",
    year: "",
    category: "campaigns",
    images: [
      "images/commercial/charlotte-tilbury/charlotte-tilbury-075.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-080.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-078.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-083.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-057.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-047.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-045.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-042.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-030.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-053.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-066.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-004.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-108.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-107.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-109.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-117.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-119.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-094.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-087.jpg",
    ],
  },

  {
    title: "Summer Fridays",
    featured: true,
    client: "Summer Fridays",
    year: "",
    category: "campaigns",
    images: [
      "images/commercial/summer-fridays/summer-fridays-012.jpg",
      "images/commercial/summer-fridays/summer-fridays-019.jpg",
      "images/commercial/summer-fridays/summer-fridays-006.jpg",
      "images/commercial/summer-fridays/summer-fridays-009.jpg",
      "images/commercial/summer-fridays/summer-fridays-014.jpg",
      "images/commercial/summer-fridays/summer-fridays-023.jpg",
      "images/commercial/summer-fridays/summer-fridays-017.jpg",
      "images/commercial/summer-fridays/summer-fridays-028.jpg",
      "images/commercial/summer-fridays/summer-fridays-037.jpg",
      "images/commercial/summer-fridays/summer-fridays-038.jpg",
    ],
  },

  {
    title: "Tatcha",
    featured: true,
    client: "Tatcha",
    year: "",
    category: "campaigns",
    images: [
      "images/commercial/tatcha/tatcha-028.jpg",
      "images/commercial/tatcha/tatcha-002.jpg",
      "images/commercial/tatcha/tatcha-022.jpg",
      "images/commercial/tatcha/tatcha-025.jpg",
      "images/commercial/tatcha/tatcha-015.jpg",
      "images/commercial/tatcha/tatcha-016.jpg",
    ],
  },

  {
    title: "Tessi",
    featured: true,
    client: "Tessi",
    year: "",
    category: "campaigns",
    images: [
      "images/commercial/tessi/tessi-063.jpg",
      "images/commercial/tessi/tessi-078.jpg",
      "images/commercial/tessi/tessi-022.jpg",
      "images/commercial/tessi/tessi-077.jpg",
      "images/commercial/tessi/tessi-011.jpg",
      "images/commercial/tessi/tessi-142.jpg",
      "images/commercial/tessi/tessi-076.jpg",
      "images/commercial/tessi/tessi-153.jpg",
      "images/commercial/tessi/tessi-185.jpg",
      "images/commercial/tessi/tessi-008.jpg",
      "images/commercial/tessi/tessi-086.jpg",
      "images/commercial/tessi/tessi-026.jpg",
      "images/commercial/tessi/tessi-186.jpg",
      "images/commercial/tessi/tessi-161.jpg",
    ],
  },

  {
    title: "Product",
    featured: true,
    client: "",
    year: "",
    category: "product",
    images: [
      "images/commercial/product/product-002.jpg",
      "images/commercial/product/product-003.jpg",
      "images/commercial/product/product-001.jpg",
      "images/commercial/product/product-007.jpg",
      "images/commercial/product/product-004.jpg",
      "images/commercial/product/product-005.jpg",
      "images/commercial/product/product-006.jpg",
      "images/commercial/product/product-008.jpg",
      "images/commercial/product/product-009.jpg",
    ],
  },

  {
    title: "Acacia",
    featured: true,
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/acacia/acacia-008.jpg",
      "images/commercial/acacia/acacia-003.jpg",
      "images/commercial/acacia/acacia-005.jpg",
      "images/commercial/acacia/acacia-006.jpg",
      "images/commercial/acacia/acacia-007.jpg",
      "images/commercial/acacia/acacia-009.jpg",
      "images/commercial/acacia/acacia-010.jpg",
      "images/commercial/acacia/acacia-011.jpg",
    ],
  },

  {
    title: "Chloe",
    featured: true,
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/chloe/chloe-001.jpg",
      "images/commercial/chloe/chloe-002.jpg",
      "images/commercial/chloe/chloe-003.jpg",
      "images/commercial/chloe/chloe-005.jpg",
      "images/commercial/chloe/chloe-007.jpg",
      "images/commercial/chloe/chloe-008.jpg",
      "images/commercial/chloe/chloe-010.jpg",
      "images/commercial/chloe/chloe-011.jpg",
      "images/commercial/chloe/chloe-012.jpg",
      "images/commercial/chloe/chloe-014.jpg",
      "images/commercial/chloe/chloe-015.jpg",
      "images/commercial/chloe/chloe-016.jpg",
    ],
  },

  {
    title: "Courtney",
    featured: true,
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/courtney/courtney-001.jpg",
      "images/commercial/courtney/courtney-005.jpg",
      "images/commercial/courtney/courtney-009.jpg",
      "images/commercial/courtney/courtney-014.jpg",
      "images/commercial/courtney/courtney-018.jpg",
      "images/commercial/courtney/courtney-022.jpg",
      "images/commercial/courtney/courtney-027.jpg",
      "images/commercial/courtney/courtney-031.jpg",
      "images/commercial/courtney/courtney-036.jpg",
      "images/commercial/courtney/courtney-040.jpg",
      "images/commercial/courtney/courtney-044.jpg",
      "images/commercial/courtney/courtney-048.jpg",
    ],
  },

  {
    title: "Nail Editorial",
    featured: true,
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/nail-editorial/nail-editorial-025.jpg",
      "images/commercial/nail-editorial/nail-editorial-019.jpg",
      "images/commercial/nail-editorial/nail-editorial-001.jpg",
      "images/commercial/nail-editorial/nail-editorial-007.jpg",
      "images/commercial/nail-editorial/nail-editorial-013.jpg",
      "images/commercial/nail-editorial/nail-editorial-030.jpg",
      "images/commercial/nail-editorial/nail-editorial-036.jpg",
      "images/commercial/nail-editorial/nail-editorial-044.jpg",
      "images/commercial/nail-editorial/nail-editorial-050.jpg",
      "images/commercial/nail-editorial/nail-editorial-055.jpg",
      "images/commercial/nail-editorial/nail-editorial-061.jpg",
      "images/commercial/nail-editorial/nail-editorial-067.jpg",
      "images/commercial/nail-editorial/nail-editorial-073.jpg",
      "images/commercial/nail-editorial/nail-editorial-078.jpg",
      "images/commercial/nail-editorial/nail-editorial-084.jpg",
      "images/commercial/nail-editorial/nail-editorial-092.jpg",
    ],
  },

  {
    title: "Alicia",
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/alicia/alicia-001.jpg",
      "images/commercial/alicia/alicia-003.jpg",
      "images/commercial/alicia/alicia-005.jpg",
      "images/commercial/alicia/alicia-007.jpg",
      "images/commercial/alicia/alicia-009.jpg",
      "images/commercial/alicia/alicia-011.jpg",
      "images/commercial/alicia/alicia-013.jpg",
      "images/commercial/alicia/alicia-015.jpg",
      "images/commercial/alicia/alicia-017.jpg",
      "images/commercial/alicia/alicia-019.jpg",
      "images/commercial/alicia/alicia-021.jpg",
      "images/commercial/alicia/alicia-023.jpg",
    ],
  },

  {
    title: "Cameron",
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/cameron/cameron-001.jpg",
      "images/commercial/cameron/cameron-004.jpg",
      "images/commercial/cameron/cameron-008.jpg",
      "images/commercial/cameron/cameron-011.jpg",
      "images/commercial/cameron/cameron-016.jpg",
      "images/commercial/cameron/cameron-020.jpg",
      "images/commercial/cameron/cameron-024.jpg",
      "images/commercial/cameron/cameron-028.jpg",
      "images/commercial/cameron/cameron-031.jpg",
      "images/commercial/cameron/cameron-035.jpg",
      "images/commercial/cameron/cameron-039.jpg",
      "images/commercial/cameron/cameron-043.jpg",
    ],
  },

  {
    title: "Chase",
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/chase/chase-001.jpg",
      "images/commercial/chase/chase-002.jpg",
      "images/commercial/chase/chase-003.jpg",
      "images/commercial/chase/chase-004.jpg",
      "images/commercial/chase/chase-005.jpg",
      "images/commercial/chase/chase-006.jpg",
    ],
  },

  {
    title: "Destiny",
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/destiny/destiny-001.jpg",
      "images/commercial/destiny/destiny-002.jpg",
      "images/commercial/destiny/destiny-003.jpg",
      "images/commercial/destiny/destiny-005.jpg",
      "images/commercial/destiny/destiny-006.jpg",
      "images/commercial/destiny/destiny-008.jpg",
      "images/commercial/destiny/destiny-009.jpg",
      "images/commercial/destiny/destiny-010.jpg",
      "images/commercial/destiny/destiny-012.jpg",
      "images/commercial/destiny/destiny-014.jpg",
      "images/commercial/destiny/destiny-016.jpg",
      "images/commercial/destiny/destiny-017.jpg",
    ],
  },

  {
    title: "Lucas",
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/lucas/lucas-001.jpg",
      "images/commercial/lucas/lucas-002.jpg",
      "images/commercial/lucas/lucas-003.jpg",
      "images/commercial/lucas/lucas-004.jpg",
      "images/commercial/lucas/lucas-005.jpg",
      "images/commercial/lucas/lucas-006.jpg",
      "images/commercial/lucas/lucas-007.jpg",
      "images/commercial/lucas/lucas-008.jpg",
      "images/commercial/lucas/lucas-009.jpg",
      "images/commercial/lucas/lucas-010.jpg",
    ],
  },

  {
    title: "O Models",
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/o-models/o-models-001.jpg",
      "images/commercial/o-models/o-models-006.jpg",
      "images/commercial/o-models/o-models-011.jpg",
      "images/commercial/o-models/o-models-016.jpg",
      "images/commercial/o-models/o-models-021.jpg",
      "images/commercial/o-models/o-models-026.jpg",
      "images/commercial/o-models/o-models-063.jpg",
      "images/commercial/o-models/o-models-068.jpg",
      "images/commercial/o-models/o-models-073.jpg",
      "images/commercial/o-models/o-models-078.jpg",
      "images/commercial/o-models/o-models-098.jpg",
      "images/commercial/o-models/o-models-103.jpg",
    ],
  },

  {
    title: "Tabatha",
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/tabatha/tabatha-006.jpg",
      "images/commercial/tabatha/tabatha-001.jpg",
      "images/commercial/tabatha/tabatha-004.jpg",
      "images/commercial/tabatha/tabatha-011.jpg",
      "images/commercial/tabatha/tabatha-013.jpg",
      "images/commercial/tabatha/tabatha-017.jpg",
      "images/commercial/tabatha/tabatha-021.jpg",
      "images/commercial/tabatha/tabatha-027.jpg",
      "images/commercial/tabatha/tabatha-031.jpg",
      "images/commercial/tabatha/tabatha-037.jpg",
      "images/commercial/tabatha/tabatha-043.jpg",
      "images/commercial/tabatha/tabatha-047.jpg",
      "images/commercial/tabatha/tabatha-071.jpg",
      "images/commercial/tabatha/tabatha-077.jpg",
    ],
  },

  {
    title: "Don Kaka",
    featured: true,
    client: "Don Kaka",
    year: "",
    category: "fashion",
    images: [
      "images/commercial/don-kaka/don-kaka-025.jpg",
      "images/commercial/don-kaka/don-kaka-001.jpg",
      "images/commercial/don-kaka/don-kaka-002.jpg",
      "images/commercial/don-kaka/don-kaka-009.jpg",
      "images/commercial/don-kaka/don-kaka-011.jpg",
      "images/commercial/don-kaka/don-kaka-015.jpg",
      "images/commercial/don-kaka/don-kaka-017.jpg",
      "images/commercial/don-kaka/don-kaka-018.jpg",
      "images/commercial/don-kaka/don-kaka-024.jpg",
      "images/commercial/don-kaka/don-kaka-023.jpg",
      "images/commercial/don-kaka/don-kaka-007.jpg",
      "images/commercial/don-kaka/don-kaka-014.jpg",
      "images/commercial/don-kaka/don-kaka-016.jpg",
      "images/commercial/don-kaka/don-kaka-019.jpg",
      "images/commercial/don-kaka/don-kaka-021.jpg",
    ],
  },

  {
    title: "Hope",
    client: "",
    year: "",
    category: "fashion",
    images: [
      "images/commercial/hope/hope-001.jpg",
      "images/commercial/hope/hope-002.jpg",
      "images/commercial/hope/hope-003.jpg",
      "images/commercial/hope/hope-005.jpg",
      "images/commercial/hope/hope-006.jpg",
      "images/commercial/hope/hope-007.jpg",
      "images/commercial/hope/hope-009.jpg",
      "images/commercial/hope/hope-010.jpg",
      "images/commercial/hope/hope-011.jpg",
      "images/commercial/hope/hope-012.jpg",
      "images/commercial/hope/hope-013.jpg",
      "images/commercial/hope/hope-014.jpg",
    ],
  },

  {
    title: "Isabel",
    client: "",
    year: "",
    category: "fashion",
    images: [
      "images/commercial/isabel/isabel-001.jpg",
      "images/commercial/isabel/isabel-002.jpg",
      "images/commercial/isabel/isabel-003.jpg",
      "images/commercial/isabel/isabel-004.jpg",
      "images/commercial/isabel/isabel-005.jpg",
      "images/commercial/isabel/isabel-006.jpg",
      "images/commercial/isabel/isabel-007.jpg",
      "images/commercial/isabel/isabel-008.jpg",
      "images/commercial/isabel/isabel-009.jpg",
      "images/commercial/isabel/isabel-010.jpg",
    ],
  },

  {
    title: "Jordan",
    client: "",
    year: "",
    category: "fashion",
    images: [
      "images/commercial/jordan/jordan-001.jpg",
      "images/commercial/jordan/jordan-004.jpg",
      "images/commercial/jordan/jordan-007.jpg",
      "images/commercial/jordan/jordan-010.jpg",
      "images/commercial/jordan/jordan-013.jpg",
      "images/commercial/jordan/jordan-017.jpg",
      "images/commercial/jordan/jordan-020.jpg",
      "images/commercial/jordan/jordan-023.jpg",
      "images/commercial/jordan/jordan-027.jpg",
      "images/commercial/jordan/jordan-032.jpg",
      "images/commercial/jordan/jordan-037.jpg",
      "images/commercial/jordan/jordan-040.jpg",
      "images/commercial/jordan/jordan-043.jpg",
      "images/commercial/jordan/jordan-046.jpg",
    ],
  },

  {
    title: "Serena",
    client: "",
    year: "",
    category: "fashion",
    images: [
      "images/commercial/serena/serena-036.jpg",
      "images/commercial/serena/serena-043.jpg",
      "images/commercial/serena/serena-049.jpg",
      "images/commercial/serena/serena-058.jpg",
      "images/commercial/serena/serena-064.jpg",
      "images/commercial/serena/serena-069.jpg",
      "images/commercial/serena/serena-074.jpg",
      "images/commercial/serena/serena-079.jpg",
      "images/commercial/serena/serena-085.jpg",
      "images/commercial/serena/serena-090.jpg",
      "images/commercial/serena/serena-095.jpg",
      "images/commercial/serena/serena-101.jpg",
    ],
  },
];

/* Where every inquiry goes — both the commercial form and the general one. */
const CONTACT_EMAIL = "inquiries@angelliproductions.com";

/* OPTIONAL — Formspree endpoint for the contact form.
   Leave as-is and the form falls back to opening the visitor's
   email app addressed to you (works with zero setup).
   To collect submissions in a dashboard instead, create a free
   form at https://formspree.io and paste its endpoint here. */
const FORMSPREE_ENDPOINT = ""; // e.g. "https://formspree.io/f/abcdwxyz"
