/* ============================================================
   ANGELLI PRODUCTIONS — Commercial Work
   ------------------------------------------------------------
   EDIT THIS BY HAND, OR USE THE CURATION TOOL:
       http://localhost:8765/curate.html
   The tool writes straight back to this file.

   ONE SHOOT = ONE PROJECT = ONE THUMBNAIL. Hovering a thumbnail
   cycles through that shoot; clicking opens it in the lightbox.

     title    — shown under the thumbnail
     client   — brand, e.g. "Charlotte Tilbury" (optional)
     year     — e.g. "2025" (optional)
     category — "campaigns" | "product" | "beauty" | "fashion"
     images   — array of paths. THE FIRST ONE IS THE COVER.
     featured — add `featured: true` to put a project on SELECTED.
   ============================================================ */

const COMMERCIAL_PROJECTS = [

  {
    title: "Charlotte Tilbury",
    featured: true,
    client: "Charlotte Tilbury",
    year: "",
    category: "campaigns",
    images: [
      "images/commercial/charlotte-tilbury/charlotte-tilbury-07.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-01.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-02.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-03.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-04.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-05.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-06.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-08.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-09.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-10.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-11.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-12.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-13.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-14.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-15.jpg",
      "images/commercial/charlotte-tilbury/charlotte-tilbury-16.jpg",
    ],
  },

  {
    title: "Summer Fridays",
    featured: true,
    client: "Summer Fridays",
    year: "",
    category: "campaigns",
    images: [
      "images/commercial/summer-fridays/summer-fridays-05.jpg",
      "images/commercial/summer-fridays/summer-fridays-01.jpg",
      "images/commercial/summer-fridays/summer-fridays-02.jpg",
      "images/commercial/summer-fridays/summer-fridays-03.jpg",
      "images/commercial/summer-fridays/summer-fridays-04.jpg",
      "images/commercial/summer-fridays/summer-fridays-06.jpg",
      "images/commercial/summer-fridays/summer-fridays-07.jpg",
      "images/commercial/summer-fridays/summer-fridays-08.jpg",
      "images/commercial/summer-fridays/summer-fridays-09.jpg",
      "images/commercial/summer-fridays/summer-fridays-10.jpg",
      "images/commercial/summer-fridays/summer-fridays-11.jpg",
      "images/commercial/summer-fridays/summer-fridays-12.jpg",
      "images/commercial/summer-fridays/summer-fridays-13.jpg",
      "images/commercial/summer-fridays/summer-fridays-14.jpg",
    ],
  },

  {
    title: "Tatcha",
    featured: true,
    client: "Tatcha",
    year: "",
    category: "campaigns",
    images: [
      "images/commercial/tatcha/tatcha-01.jpg",
      "images/commercial/tatcha/tatcha-02.jpg",
      "images/commercial/tatcha/tatcha-03.jpg",
      "images/commercial/tatcha/tatcha-04.jpg",
      "images/commercial/tatcha/tatcha-05.jpg",
      "images/commercial/tatcha/tatcha-06.jpg",
      "images/commercial/tatcha/tatcha-07.jpg",
      "images/commercial/tatcha/tatcha-08.jpg",
    ],
  },

  {
    title: "Tessi",
    featured: true,
    client: "Tessi",
    year: "",
    category: "campaigns",
    images: [
      "images/commercial/tessi/tessi-18.jpg",
      "images/commercial/tessi/tessi-01.jpg",
      "images/commercial/tessi/tessi-02.jpg",
      "images/commercial/tessi/tessi-03.jpg",
      "images/commercial/tessi/tessi-04.jpg",
      "images/commercial/tessi/tessi-05.jpg",
      "images/commercial/tessi/tessi-06.jpg",
      "images/commercial/tessi/tessi-07.jpg",
      "images/commercial/tessi/tessi-08.jpg",
      "images/commercial/tessi/tessi-09.jpg",
      "images/commercial/tessi/tessi-10.jpg",
      "images/commercial/tessi/tessi-11.jpg",
      "images/commercial/tessi/tessi-12.jpg",
      "images/commercial/tessi/tessi-13.jpg",
      "images/commercial/tessi/tessi-14.jpg",
      "images/commercial/tessi/tessi-15.jpg",
      "images/commercial/tessi/tessi-16.jpg",
      "images/commercial/tessi/tessi-17.jpg",
    ],
  },

  {
    title: "Product",
    featured: true,
    client: "",
    year: "",
    category: "product",
    images: [
      "images/commercial/product/product-01.jpg",
      "images/commercial/product/product-02.jpg",
      "images/commercial/product/product-03.jpg",
      "images/commercial/product/product-04.jpg",
      "images/commercial/product/product-05.jpg",
      "images/commercial/product/product-06.jpg",
      "images/commercial/product/product-07.jpg",
      "images/commercial/product/product-08.jpg",
      "images/commercial/product/product-09.jpg",
      "images/commercial/product/product-10.jpg",
      "images/commercial/product/product-11.jpg",
      "images/commercial/product/product-12.jpg",
      "images/commercial/product/product-13.jpg",
    ],
  },

  {
    title: "Acacia",
    featured: true,
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/acacia/acacia-03.jpg",
      "images/commercial/acacia/acacia-04.jpg",
      "images/commercial/acacia/acacia-05.jpg",
      "images/commercial/acacia/acacia-06.jpg",
      "images/commercial/acacia/acacia-07.jpg",
      "images/commercial/acacia/acacia-08.jpg",
      "images/commercial/acacia/acacia-09.jpg",
      "images/commercial/acacia/acacia-10.jpg",
      "images/commercial/acacia/acacia-11.jpg",
      "images/commercial/acacia/acacia-12.jpg",
    ],
  },

  {
    title: "Chloe",
    featured: true,
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/chloe/chloe-01.jpg",
      "images/commercial/chloe/chloe-02.jpg",
      "images/commercial/chloe/chloe-03.jpg",
      "images/commercial/chloe/chloe-04.jpg",
      "images/commercial/chloe/chloe-05.jpg",
      "images/commercial/chloe/chloe-06.jpg",
      "images/commercial/chloe/chloe-07.jpg",
      "images/commercial/chloe/chloe-08.jpg",
      "images/commercial/chloe/chloe-09.jpg",
      "images/commercial/chloe/chloe-10.jpg",
      "images/commercial/chloe/chloe-11.jpg",
    ],
  },

  {
    title: "Courtney",
    featured: true,
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/courtney/courtney-01.jpg",
      "images/commercial/courtney/courtney-02.jpg",
      "images/commercial/courtney/courtney-03.jpg",
      "images/commercial/courtney/courtney-04.jpg",
      "images/commercial/courtney/courtney-05.jpg",
      "images/commercial/courtney/courtney-06.jpg",
      "images/commercial/courtney/courtney-07.jpg",
      "images/commercial/courtney/courtney-08.jpg",
      "images/commercial/courtney/courtney-09.jpg",
      "images/commercial/courtney/courtney-10.jpg",
      "images/commercial/courtney/courtney-11.jpg",
      "images/commercial/courtney/courtney-12.jpg",
    ],
  },

  {
    title: "Nail Editorial",
    featured: true,
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/nail-editorial/nail-editorial-01.jpg",
      "images/commercial/nail-editorial/nail-editorial-02.jpg",
      "images/commercial/nail-editorial/nail-editorial-03.jpg",
      "images/commercial/nail-editorial/nail-editorial-04.jpg",
      "images/commercial/nail-editorial/nail-editorial-05.jpg",
      "images/commercial/nail-editorial/nail-editorial-06.jpg",
      "images/commercial/nail-editorial/nail-editorial-07.jpg",
      "images/commercial/nail-editorial/nail-editorial-08.jpg",
      "images/commercial/nail-editorial/nail-editorial-09.jpg",
      "images/commercial/nail-editorial/nail-editorial-10.jpg",
      "images/commercial/nail-editorial/nail-editorial-11.jpg",
      "images/commercial/nail-editorial/nail-editorial-12.jpg",
      "images/commercial/nail-editorial/nail-editorial-13.jpg",
      "images/commercial/nail-editorial/nail-editorial-14.jpg",
      "images/commercial/nail-editorial/nail-editorial-15.jpg",
      "images/commercial/nail-editorial/nail-editorial-16.jpg",
    ],
  },

  {
    title: "Alicia",
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/alicia/alicia-01.jpg",
      "images/commercial/alicia/alicia-02.jpg",
      "images/commercial/alicia/alicia-03.jpg",
      "images/commercial/alicia/alicia-04.jpg",
      "images/commercial/alicia/alicia-05.jpg",
      "images/commercial/alicia/alicia-06.jpg",
      "images/commercial/alicia/alicia-07.jpg",
      "images/commercial/alicia/alicia-08.jpg",
      "images/commercial/alicia/alicia-09.jpg",
      "images/commercial/alicia/alicia-10.jpg",
      "images/commercial/alicia/alicia-11.jpg",
    ],
  },

  {
    title: "Cameron",
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/cameron/cameron-01.jpg",
      "images/commercial/cameron/cameron-02.jpg",
      "images/commercial/cameron/cameron-03.jpg",
      "images/commercial/cameron/cameron-04.jpg",
      "images/commercial/cameron/cameron-05.jpg",
      "images/commercial/cameron/cameron-06.jpg",
      "images/commercial/cameron/cameron-07.jpg",
      "images/commercial/cameron/cameron-08.jpg",
      "images/commercial/cameron/cameron-09.jpg",
      "images/commercial/cameron/cameron-10.jpg",
      "images/commercial/cameron/cameron-11.jpg",
      "images/commercial/cameron/cameron-12.jpg",
    ],
  },

  {
    title: "Chase",
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/chase/chase-01.jpg",
      "images/commercial/chase/chase-02.jpg",
      "images/commercial/chase/chase-03.jpg",
      "images/commercial/chase/chase-04.jpg",
      "images/commercial/chase/chase-05.jpg",
      "images/commercial/chase/chase-06.jpg",
    ],
  },

  {
    title: "Destiny",
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/destiny/destiny-01.jpg",
      "images/commercial/destiny/destiny-02.jpg",
      "images/commercial/destiny/destiny-03.jpg",
      "images/commercial/destiny/destiny-04.jpg",
      "images/commercial/destiny/destiny-05.jpg",
      "images/commercial/destiny/destiny-06.jpg",
      "images/commercial/destiny/destiny-07.jpg",
      "images/commercial/destiny/destiny-08.jpg",
      "images/commercial/destiny/destiny-09.jpg",
      "images/commercial/destiny/destiny-10.jpg",
      "images/commercial/destiny/destiny-11.jpg",
    ],
  },

  {
    title: "Lucas",
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/lucas/lucas-01.jpg",
      "images/commercial/lucas/lucas-02.jpg",
      "images/commercial/lucas/lucas-03.jpg",
      "images/commercial/lucas/lucas-04.jpg",
      "images/commercial/lucas/lucas-05.jpg",
      "images/commercial/lucas/lucas-06.jpg",
      "images/commercial/lucas/lucas-07.jpg",
      "images/commercial/lucas/lucas-08.jpg",
      "images/commercial/lucas/lucas-09.jpg",
      "images/commercial/lucas/lucas-10.jpg",
    ],
  },

  {
    title: "O Models",
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/o-models/o-models-01.jpg",
      "images/commercial/o-models/o-models-02.jpg",
      "images/commercial/o-models/o-models-03.jpg",
      "images/commercial/o-models/o-models-04.jpg",
      "images/commercial/o-models/o-models-05.jpg",
      "images/commercial/o-models/o-models-06.jpg",
      "images/commercial/o-models/o-models-07.jpg",
      "images/commercial/o-models/o-models-08.jpg",
      "images/commercial/o-models/o-models-09.jpg",
      "images/commercial/o-models/o-models-10.jpg",
      "images/commercial/o-models/o-models-11.jpg",
      "images/commercial/o-models/o-models-12.jpg",
    ],
  },

  {
    title: "Tabatha",
    client: "",
    year: "",
    category: "beauty",
    images: [
      "images/commercial/tabatha/tabatha-03.jpg",
      "images/commercial/tabatha/tabatha-01.jpg",
      "images/commercial/tabatha/tabatha-02.jpg",
      "images/commercial/tabatha/tabatha-04.jpg",
      "images/commercial/tabatha/tabatha-05.jpg",
      "images/commercial/tabatha/tabatha-06.jpg",
      "images/commercial/tabatha/tabatha-07.jpg",
      "images/commercial/tabatha/tabatha-08.jpg",
      "images/commercial/tabatha/tabatha-09.jpg",
      "images/commercial/tabatha/tabatha-10.jpg",
      "images/commercial/tabatha/tabatha-11.jpg",
      "images/commercial/tabatha/tabatha-12.jpg",
      "images/commercial/tabatha/tabatha-13.jpg",
      "images/commercial/tabatha/tabatha-14.jpg",
    ],
  },

  {
    title: "Jordan",
    featured: true,
    client: "",
    year: "",
    category: "fashion",
    images: [
      "images/commercial/jordan/jordan-01.jpg",
      "images/commercial/jordan/jordan-02.jpg",
      "images/commercial/jordan/jordan-03.jpg",
      "images/commercial/jordan/jordan-04.jpg",
      "images/commercial/jordan/jordan-05.jpg",
      "images/commercial/jordan/jordan-06.jpg",
      "images/commercial/jordan/jordan-07.jpg",
      "images/commercial/jordan/jordan-08.jpg",
      "images/commercial/jordan/jordan-09.jpg",
      "images/commercial/jordan/jordan-10.jpg",
      "images/commercial/jordan/jordan-11.jpg",
      "images/commercial/jordan/jordan-12.jpg",
      "images/commercial/jordan/jordan-13.jpg",
      "images/commercial/jordan/jordan-14.jpg",
    ],
  },

  {
    title: "Hope",
    client: "",
    year: "",
    category: "fashion",
    images: [
      "images/commercial/hope/hope-01.jpg",
      "images/commercial/hope/hope-02.jpg",
      "images/commercial/hope/hope-03.jpg",
      "images/commercial/hope/hope-04.jpg",
      "images/commercial/hope/hope-05.jpg",
      "images/commercial/hope/hope-06.jpg",
      "images/commercial/hope/hope-07.jpg",
      "images/commercial/hope/hope-08.jpg",
      "images/commercial/hope/hope-09.jpg",
      "images/commercial/hope/hope-10.jpg",
    ],
  },

  {
    title: "Isabel",
    client: "",
    year: "",
    category: "fashion",
    images: [
      "images/commercial/isabel/isabel-01.jpg",
      "images/commercial/isabel/isabel-02.jpg",
      "images/commercial/isabel/isabel-03.jpg",
      "images/commercial/isabel/isabel-04.jpg",
      "images/commercial/isabel/isabel-05.jpg",
      "images/commercial/isabel/isabel-06.jpg",
      "images/commercial/isabel/isabel-07.jpg",
      "images/commercial/isabel/isabel-08.jpg",
      "images/commercial/isabel/isabel-09.jpg",
      "images/commercial/isabel/isabel-10.jpg",
    ],
  },

  {
    title: "Serena",
    client: "",
    year: "",
    category: "fashion",
    images: [
      "images/commercial/serena/serena-03.jpg",
      "images/commercial/serena/serena-04.jpg",
      "images/commercial/serena/serena-05.jpg",
      "images/commercial/serena/serena-06.jpg",
      "images/commercial/serena/serena-07.jpg",
      "images/commercial/serena/serena-08.jpg",
      "images/commercial/serena/serena-09.jpg",
      "images/commercial/serena/serena-10.jpg",
      "images/commercial/serena/serena-11.jpg",
      "images/commercial/serena/serena-12.jpg",
      "images/commercial/serena/serena-13.jpg",
      "images/commercial/serena/serena-14.jpg",
    ],
  },
];

/* Where every inquiry goes — both the commercial form and the general one. */
const CONTACT_EMAIL = "inquiries@angelliproductions.com";

/* OPTIONAL — Formspree endpoint for the contact form.
   Leave as-is and the form falls back to opening the visitor's
   email app addressed to you (works with zero setup).
   To collect submissions in a dashboard instead, create a free
   form at https://formspree.io and paste its endpoint here. */
const FORMSPREE_ENDPOINT = ""; // e.g. "https://formspree.io/f/abcdwxyz"
